import type { KAPLAYCtx } from "kaplay";

// In WordPress, window.NIMSTICK_GAME_BASE points at the plugin's dist/ folder.
// In dev/preview it is undefined, so assets resolve relative to the page root.
// Character sheets come from hand-drawn art normalized by scripts/normalize-art.cjs
// (see art-manifest.json for sliceX/sliceY + frame ranges). Background and ground
// tiles are SVG-authored by scripts/gen-art.cjs.
declare global {
  interface Window {
    NIMSTICK_GAME_BASE?: string;
  }
}

const BASE =
  (typeof window !== "undefined" && window.NIMSTICK_GAME_BASE) || "";

// Cache-bust query param — bump whenever the art changes so browsers (and the
// WordPress CDN) refetch the new PNGs instead of serving stale cached copies.
const ASSET_VERSION = "5";
const url = (p: string) => `${BASE}${p}?v=${ASSET_VERSION}`;

// Number of metallic sticker ground-tile variants generated by gen-art.cjs.
export const GROUND_TILE_COUNT = 8;

export function loadAssets(k: KAPLAYCtx): void {
  k.loadSprite("stickan", url("sprites/stickan.png"), {
    sliceX: 6,
    sliceY: 3,
    anims: {
      idle: { from: 0, to: 3, loop: true, speed: 5 },
      run: { from: 4, to: 9, loop: true, speed: 14 },
      jump: { from: 10, to: 11, loop: false, speed: 8 },
      throw: { from: 12, to: 14, loop: false, speed: 18 },
      hurt: { from: 15, to: 15 },
    },
  });
  k.loadSprite("janitor", url("sprites/janitor.png"), {
    sliceX: 6,
    sliceY: 2,
    anims: {
      idle: { from: 0, to: 2, loop: true, speed: 3 },
      run: { from: 3, to: 8, loop: true, speed: 5 },
    },
  });
  k.loadSprite("granny", url("sprites/granny.png"), {
    sliceX: 6,
    sliceY: 2,
    anims: {
      idle: { from: 0, to: 2, loop: true, speed: 3 },
      run: { from: 3, to: 8, loop: true, speed: 3 },
    },
  });
  k.loadSprite("boss", url("sprites/boss.png"), {
    sliceX: 6,
    sliceY: 2,
    anims: {
      idle: { from: 0, to: 2, loop: true, speed: 5 },
      charge: { from: 3, to: 8, loop: true, speed: 12 },
    },
  });
  k.loadSprite("throwsticker", url("sprites/throwsticker.png"), {
    sliceX: 10,
    sliceY: 1,
    anims: { spin: { from: 0, to: 9, loop: true, speed: 18 } },
  });
  k.loadSprite("bg-city", url("sprites/bg-city.png"));
  // Metallic sticker platform tiles (variants picked at random per tile).
  for (let i = 0; i < GROUND_TILE_COUNT; i++) {
    k.loadSprite(`ground-${i}`, url(`sprites/ground-${i}.png`));
  }

  k.loadSound("jump", url("sfx/jump.wav"));
  k.loadSound("throw", url("sfx/throw.wav"));
  k.loadSound("stomp", url("sfx/stomp.wav"));
  k.loadSound("coin", url("sfx/coin.wav"));
  k.loadSound("hurt", url("sfx/hurt.wav"));
  k.loadSound("peel", url("sfx/peel.wav"));
}
