import type { KAPLAYCtx } from "kaplay";

// In WordPress, window.NIMSTICK_GAME_BASE points at the plugin's dist/ folder.
// In dev/preview it is undefined, so assets resolve relative to the page root.
// Character sheets come from hand-drawn art normalized by scripts/normalize-art.cjs
// (see art-manifest.json for sliceX/sliceY + frame ranges). Background and ground
// tiles are SVG-authored by scripts/gen-art.cjs.
declare global {
  interface Window {
    NIMSTICK_GAME_BASE?: string;
  }
}

const BASE =
  (typeof window !== "undefined" && window.NIMSTICK_GAME_BASE) || "";

// Number of metallic sticker ground-tile variants generated by gen-art.cjs.
export const GROUND_TILE_COUNT = 8;

export function loadAssets(k: KAPLAYCtx): void {
  k.loadSprite("stickan", BASE + "sprites/stickan.png", {
    sliceX: 6,
    sliceY: 3,
    anims: {
      idle: { from: 0, to: 2, loop: true, speed: 6 },
      run: { from: 3, to: 8, loop: true, speed: 14 },
      jump: { from: 9, to: 10, loop: false, speed: 8 },
      throw: { from: 11, to: 13, loop: false, speed: 18 },
      hurt: { from: 14, to: 14 },
    },
  });
  k.loadSprite("janitor", BASE + "sprites/janitor.png", {
    sliceX: 6,
    sliceY: 2,
    anims: {
      idle: { from: 0, to: 2, loop: true, speed: 4 },
      run: { from: 3, to: 8, loop: true, speed: 6 },
    },
  });
  k.loadSprite("granny", BASE + "sprites/granny.png", {
    sliceX: 6,
    sliceY: 2,
    anims: {
      idle: { from: 0, to: 2, loop: true, speed: 4 },
      run: { from: 3, to: 8, loop: true, speed: 4 },
    },
  });
  k.loadSprite("boss", BASE + "sprites/boss.png", {
    sliceX: 6,
    sliceY: 2,
    anims: {
      idle: { from: 0, to: 2, loop: true, speed: 5 },
      charge: { from: 3, to: 8, loop: true, speed: 12 },
    },
  });
  k.loadSprite("bg-city", BASE + "sprites/bg-city.png");
  // Metallic sticker platform tiles (variants picked at random per tile).
  for (let i = 0; i < GROUND_TILE_COUNT; i++) {
    k.loadSprite(`ground-${i}`, BASE + `sprites/ground-${i}.png`);
  }

  k.loadSound("jump", BASE + "sfx/jump.wav");
  k.loadSound("throw", BASE + "sfx/throw.wav");
  k.loadSound("stomp", BASE + "sfx/stomp.wav");
  k.loadSound("coin", BASE + "sfx/coin.wav");
  k.loadSound("hurt", BASE + "sfx/hurt.wav");
  k.loadSound("peel", BASE + "sfx/peel.wav");
}
